# Site
#repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Victor E. Chocho
title: Biologist
email: vechocho@gmail.com
website: vechocho.github.io
blog: vechocho.github.io/blog

# Social links
twitter_username: vechocho
# github_username:  vechocho
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: vechocho
linkedin_username: vechocho
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Victor and I'm a biologist. Currently workink on biosafety at Environment Ministry of Ecuador.

  I am most skilled in: <mark>environmental policies</mark> and <mark>geographical information system</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in biology and policies, some of my other interests and hobbies are:
   - Gaming
   - Teaching
   #- [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
